# Generated by Django 6.0.2 on 2026-02-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('GALAXIA', 'Galáxia'), ('ESTRELA', 'Estrela'), ('PLANETA', 'Planeta'), ('NEBULOSA', 'Nebulosa')], default='GALAXIA', max_length=100),
        ),
    ]
