# Generated by Django 6.0.2 on 2026-02-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('GALAXIA', 'Galáxia'), ('ESTRELA', 'Estrela'), ('PLANETA', 'Planeta'), ('NEBULOSA', 'Nebulosa'), ('LUA', 'Lua')], default='GALAXIA', max_length=100),
        ),
    ]
